// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using QuerySplitting.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace QuerySplitting.Data
{
    public partial interface IContextProcedures
    {
        Task<int> usp_AddCustomerAsync(string CompanyName, int? ContactId, string Street, string City, string Region, string PostalCode, int? CountryIdentifier, string Phone, int? ContactTypeIdentifier, OutputParameter<int?> Identifier, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_AddCustomer1Result>> usp_AddCustomer1Async(string CompanyName, int? ContactId, string Street, string City, string Region, string PostalCode, int? CountryIdentifier, string Phone, int? ContactTypeIdentifier, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_CustomersByCountryResult>> usp_CustomersByCountryAsync(int? CountryIdentifier, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_CustomersOrderByResult>> usp_CustomersOrderByAsync(string orderby, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> usp_MaxLengthOfColumnsForTableAsync(string TableName, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_SelectCatCountryContactTypeResult>> usp_SelectCatCountryContactTypeAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<uspSupplierForProductResult>> uspSupplierForProductAsync(int? ProductIdentifier, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
